[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vibecheck"
version = "1.0.0"
dependencies = [
    "flask==3.1.1",
    "gunicorn==23.0.0",
    "firebase-admin==6.9.0",
    "flask-wtf==1.2.2",
    "wtforms==3.2.0",
    "openai==1.58.1",
    "python-dotenv==1.0.1"
]
